### ISSUE TITLE
Can't get preview to show

### ISSUE THREAD

**Issue by Bryce-Davidson** [rad4day/anki-editor-preview-plugin#2]
I've set up this add-on for the Anki desktop as described with the add-on code.

The preview button shows up in the editor, but when I click it nothing happens and the live preview is not visible as seen in the documentation. 

I only have Image occlusion enhanced & Anki Connect installed.

Thanks for writing this add-on!

Anki: Version ⁨2.1.44
MacOS: Big Sur 11.6

**Comment by rad4day** [comment]
I can confirm that the addon does not work on 2.1.44 but does as of 2.1.45. 

Generally, I'd recommend upgrading. The problem seems to be, that they changed the required js files that have to be loaded into the reviewer screen, sadly there seems to be no "easy way" to get those. I'll publish a fix soon.

**Comment by rad4day** [comment]
It should be resizeable. There should be a bar on top you can use to drag the editor/preview ratio.

**Comment by Bryce-Davidson** [comment]
You're making may day, thanks so much :) appreciate the work you've put into this!
